webempresa/blog/urls.py
from django.urls import path
from . import  views
app_name='blog'
urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<int:category_id>/', views.category, name='category'),

]

webempresa/contact/urls.py
from django.urls import path
from . import  views
app_name='contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),

]

webempresa/core/urls.py
from django.urls import path
from . import views
app_name='core'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('store/', views.store, name='store'),
]

webempresa/pages/urls.py
from django.urls import path
from . import views
app_name='pages'
urlpatterns = [
    path('page/<int:page_id>/', views.page, name='page'),
]

webempresa/services/urls.py
from django.urls import path
from . import views
app_name='services'
urlpatterns = [
    path('services/', views.services, name='services'),
]

webempresa/webempresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('services.urls', namespace='services')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('pages.urls', namespace='pages')),
    path('', include('contact.urls', namespace='contact')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

webempresa/blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import  User

class Category(models.Model):
    name=models.CharField(max_length=100, verbose_name='nombre')
    created = models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
        ordering = ['-created']

class Post(models.Model):
    title=models.CharField(max_length=200, verbose_name='Titulo')
    content=models.TextField(verbose_name='contenido')
    published=models.DateTimeField(verbose_name='fecha de publicacion', default=now)
    image=models.ImageField(verbose_name='imagen', upload_to='blog', null=True, blank=True)
    author=models.ForeignKey(User, verbose_name='author', on_delete=models.CASCADE)
    categories=models.ManyToManyField(Category, verbose_name='categorias', related_name='get_post')

    created = models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ['-created']

webempresa/contact/models.py
from django.db import models

# Create your models here.

webempresa/core/models.py
from django.db import models

# Create your models here.

webempresa/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField
class Pages(models.Model):
    key=models.SlugField(verbose_name="Nombre Clave", max_length=100, unique=True)
    title=models.CharField(verbose_name="titulo", max_length=200)
    content=RichTextField(verbose_name='contenido')
    order=models.SmallIntegerField(verbose_name='orden', default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Página'
        verbose_name_plural = 'Páginas'
        ordering = ['order','-title']
# Create your models here.

webempresa/services/models.py
from django.db import models
class Service(models.Model):
    title=models.CharField(max_length=200, verbose_name='titulo')
    subtitle=models.CharField(max_length=200, verbose_name='subtitulo')
    content=models.TextField(verbose_name='contenido')
    image=models.ImageField(upload_to='services', verbose_name='imagen')
    created=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')
    updated=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='servicio'
        verbose_name_plural='servicios'
        ordering=['-created']
# Create your models here.

webempresa/social/models.py
from django.db import models


class Link(models.Model):
    key=models.SlugField(verbose_name="Nombre Clave", max_length=100, unique=True)
    name=models.CharField(verbose_name="Red Social", max_length=200)
    url=models.URLField(verbose_name='enlace', max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Red Social'
        verbose_name_plural = 'Redes Sociales'
        ordering = ['-name']

webempresa/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name=forms.CharField(label='Nombre', required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'tu nombre'}))
    email=forms.EmailField(label='email', required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'tu email'}))
    content=forms.CharField(label='Contenido', required=True, widget=forms.Textarea(attrs={'class':'form-control', 'rows':4, 'placeholder':'ostias tio'}))

webempresa/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
def blog(request):
    posts=Post.objects.all().order_by('-published')
    return render(request, 'blog/blog.html', {'posts':posts})

def category(request, category_id):
    category=get_object_or_404(Category, id=category_id)
    return render(request, "blog/category.html", {'category':category})

# Create your views here.

webempresa/contact/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.mail import EmailMessage
from .forms import ContactForm
def contact(request):
    form = ContactForm()
    if request.POST:
        print('entro al post')
        form=ContactForm(data=request.POST)
        if form.is_valid():
            name=request.POST.get('name', '')
            email=request.POST.get('email', '')
            content=request.POST.get('content', '')
            email=EmailMessage(
                "LA CAFETERIA",
                "De {}<{}>\n\nEsribió\n{}".format(name, email, content),
                "no_contestar_este_correo@inbox.emailtrap.io",
                ['xer131@hotmail.com'],
                reply_to=[email]
            )
            try:
                email.send()
            except:
                #Algo salió mal
                return redirect(reverse('contact:contact')+'?fail')
            return redirect(reverse('contact:contact')+'?ok')
    else:
        print('no entró al post')
    return render(request, 'contact/contact.html', {'form':form})
# Create your views here.

webempresa/core/views.py
from django.shortcuts import render, HttpResponse

def home(request):
    return render(request, 'core/home.html')
def about(request):
    return render(request, 'core/about.html')
def store(request):
    return render(request, 'core/store.html')
def contact(request):
    return render(request, 'core/contact.html')

# Create your views here.

webempresa/pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Pages

def page(request, page_id):
    page=get_object_or_404(Pages, pk=page_id)
    return render(request, 'pages/sample.html', {'page':page})
# Create your views here.

webempresa/services/views.py
from django.shortcuts import render
from .models import Service
def services(request):
    services=Service.objects.all()
    return render(request, 'services/services.html', {'services':services})
# Create your views here.

webempresa/social/views.py
from django.shortcuts import render

# Create your views here.

webempresa/blog/templates/blog/blog.html
{% extends 'core/base.html' %}
{% block title %}blog{% endblock %}
{% block sections %}
{% load static %}
    {% for post in posts %}


<section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{ post.published|date:"SHORT_DATE_FORMAT" }}</span>
                <span class="section-heading-lower">{{ post.title }}</span>
              </h2>
              <p class="mb-0">
                  {% if post.image %}

                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ post.image.url }}" alt="">
                  {% endif %}
              </p>
              <p class="mb-0 mbt">
                {{ post.content|linebreaks }}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por <em><b>{{ post.author.username }}</b></em> en <em>
                    {% for category in post.categories.all %}
                        <a href="{% url 'blog:category' category.id %}" class="link">{{ category.name }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </em>
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
    {% endfor %}
{% endblock %}

webempresa/blog/templates/blog/category.html
{% extends 'core/base.html' %}
{% block title %}blog{% endblock %}
{% block sections %}
{% load static %}
    {% for post in category.get_post.all %}
<section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{ post.published|date:"SHORT_DATE_FORMAT" }}</span>
                <span class="section-heading-lower">{{ post.title }}</span>
              </h2>
              <p class="mb-0">
                  {% if post.image %}

                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{ post.image.url }}" alt="">
                  {% endif %}
              </p>
              <p class="mb-0 mbt">
                {{ post.content|linebreaks }}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por <em><b>{{ post.author.username }}</b></em> en <em>
                    {% for category in post.categories.all %}
                        <a href="{% url 'blog:category' category.id %}" class="link">{{ category.name }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                </em>
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
    {% endfor %}
{% endblock %}

webempresa/contact/templates/contact/contact.html
{% extends 'core/base.html' %}
{% block title %}contact{% endblock %}
{% block sections %}
    {% load static %}
    <section class="page-section about-heading">
      <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/contact.jpg' %}" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Envíanos tus dudas</span>
                  <span class="section-heading-lower">Contacto</span>
                </h2>
                  {% if 'ok' in request.GET %}
                    <p><b>Su mensaje ha sido enviado correctamente</b></p>
                  {% endif %}

                <!-- Formulario de contacto -->
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Nombre *</label>
                        <div class="input-group">
                            {{ form.name }}
                        </div>
                        {{ form.name.errors }}
                    </div>
                    <div class="form-group">
                        <label>Email *</label>
                        <div class="input-group">
                            {{ form.email }}
                        </div>
                        {{ form.email.errors }}
                    </div>
                    <div class="form-group">
                        <label>Mensaje *</label>
                        <div class="input-group">
                            {{ form.content }}
                        </div>
                        {{ form.errors }}
                    </div>
                    <div class="text-center">
                        <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                    </div>
                </form>
                <!-- Fin formulario de contacto -->
                  <!--<form action="" method="POST">

                  <table>
                  </table>
                      <input type="submit" value="enviar">
                  </form>-->
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/about.html
{% extends 'core/base.html' %}
{% block title %}about{% endblock %}
{% block sections %}

    <section class="page-section about-heading">
      <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="img/about.jpg" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Tradición familiar italiana</span>
                  <span class="section-heading-lower">Nuestra historia</span>
                </h2>
                <p>Fundada en 1987 consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. </p>
                <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}La Caffettiera</title>

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static 'core/css/business-casual.css' %}" rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">L'autentico caffè d'italia</span>
      <span class="site-heading-lower">La Caffettiera</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'core:home' %}">La Caffettiera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item {% if request.path == '/' %}active {% endif %}px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:home' %}">Inicio</a>
            </li>
            <li class="nav-item {% if 'about' in request.path %}active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:about' %}">Historia</a>
            </li>
            <li class="nav-item {% if 'services' in request.path %}active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase  text-expanded" href="{% url 'services:services' %}">Servicios</a>
            </li>
            <li class="nav-item {% if 'store' in request.path %}active {% endif %}  px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'core:store' %}">Visítanos</a>
            </li>
            <li class="nav-item {% if 'contact' in request.path %}active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'contact:contact' %}">Contacto</a>
            </li>
            <li class="nav-item {% if 'blog' in request.path %}active {% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:blog' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Cabecera -->
    {% block sections %}{% endblock %}
    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
            {% if LINK_TWITTER %}
            
	        <a href="{{ LINK_TWITTER }}" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
            {% endif %}
            {% if LINK_FACEBOOK %}
        
	        <a href="{{ LINK_FACEBOOK }}" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
            {% endif %}
            {% if LINK_INSTAGRAM %}
        
	        <a href="{{ LINK_INSTAGRAM }}" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
            {% endif %}
	    </p>
        <p class="m-0 mbt">
            {% load pages_extras %}
            {% get_page_list as page_list %}
            {% for page in  page_list%}
        	    <a href="{% url 'pages:page' page.id%}" class="link">{{ page.title }}</a>
                {% if not forloop.last %}
                ·
                {% endif %}

            {% endfor %}
		</p>
        <p class="m-0 mbt1">&copy; La Caffettiera 2018</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

webempresa/core/templates/core/blog.html
{% extends 'core/base.html' %}
{% block title %}blog{% endblock %}
{% block sections %}
{% load static %}
<section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">17/05/2000</span>
                <span class="section-heading-lower">Ofertas de otoño</span>
              </h2>
              <p class="mb-0">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/img/products-01.jpg' %}" alt="">
              </p>
              <p class="mb-0 mbt">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. Aliquam eget porta mi, quis fermentum metus. Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui. Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por <em><b>Juan</b></em> en <em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span>
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}contact{% endblock %}
{% block sections %}
    {% load static %}
    <section class="page-section about-heading">
      <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/contact.jpg' %}" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Envíanos tus dudas</span>
                  <span class="section-heading-lower">Contacto</span>
                </h2>

                <!-- Formulario de contacto -->
                <form>
                    <div class="form-group">
                        <label>Nombre *</label>
                        <div class="input-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Email *</label>
                        <div class="input-group">
                            <input type="text" class="form-control">
                        </div>
                        <ul class="errorlist">
                            <li>El email no es correcto.</li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <label>Mensaje *</label>
                        <div class="input-group">
                            <textarea class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                    </div>
                </form>
                <!-- Fin formulario de contacto -->

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block title %}inicio
{% endblock %}
{% block sections %}
    {% load static %}
    <!-- Cabecera -->
    <section class="page-section clearfix">
      <div class="container">
        <div class="intro">
          <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/intro.jpg' %}" alt="">
          <div class="intro-text left-0 text-center bg-faded p-5 rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Déjate sorprender</span>
              <span class="section-heading-lower">Te gustará</span>
            </h2>
            <p class="mb-3">Trabajamos sólo con los mejores ingredientes. Una vez lo pruebes, nuestro café será la mejor forma de empezar tu rutina diaria.
            </p>
            <div class="intro-button mx-auto">
              <a class="btn btn-primary btn-xl" href="store.html">Visítanos</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Mensaje -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/sample.html
{% extends 'core/base.html' %}
{% block title %}sample{% endblock %}
{% block sections %}
    <section class="page-section about-heading">
      <div class="container">
        <div class="about-heading-content mbtm">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5 forced">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-lower">Página genérica</span>
                </h2>
                <div class="section-content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ipsum nulla, scelerisque sed dui eu, fringilla consequat velit. Integer euismod, eros sit amet facilisis rutrum, elit massa iaculis ex, vitae gravida velit dolor at nunc. Proin tincidunt pellentesque lacus. Cras egestas ligula eu purus finibus, et convallis sem rhoncus. Fusce porta magna nisl. Aenean sed quam at tellus sollicitudin facilisis. Pellentesque eleifend placerat luctus.</p>
                    <p>Proin semper nisi quam, faucibus pharetra sapien laoreet et. Proin sit amet aliquam mi. Aliquam rhoncus tortor a accumsan condimentum. Maecenas nisl urna, auctor vel aliquam ut, accumsan sit amet ipsum. Nulla at felis lorem. Phasellus sit amet consectetur lacus. Praesent eget feugiat sem. Nam odio neque, luctus quis velit sagittis, aliquet consequat arcu. Duis eget molestie turpis, nec mattis sem. Donec sem risus, rutrum quis elementum ut, pulvinar et lorem. Quisque egestas justo id justo sodales, id commodo lorem condimentum.</p>
                    <p>Mauris hendrerit felis id diam pellentesque, vel lobortis lectus sagittis. Proin efficitur dui justo, sed laoreet mi sollicitudin dapibus. Donec a convallis lorem. Sed laoreet suscipit gravida. Nam tincidunt in justo sit amet rhoncus. Donec et lectus est. Mauris a felis eu risus tincidunt congue ac sit amet orci. Nam placerat varius elit, eu vulputate nibh consequat eget.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/core/templates/core/store.html
{% extends 'core/base.html' %}
{% block title %}store{% endblock %}
{% block sections %}
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Te esperamos</span>
                <span class="section-heading-lower">Visítanos</span>
              </h2>
              <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                <li class="list-unstyled-item list-hours-item d-flex">
                  Lunes a viernes
                  <span class="ml-auto">7:00 a 20:00</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Sábados
                  <span class="ml-auto">9:00 a 17:00</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Domingos
                  <span class="ml-auto">Cerrado</span>
                </li>
              </ul>
              <p class="address mb-5">
                <em>
                  <strong>Avd. Infusiones nº 127</strong>
                  <br>
                  Barcelona
                </em>
              </p>
              <p class="mb-0">
                <small>
                  <em>Llámanos y pregunta</em>
                </small>
                <br>
                (317) 585-8468
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

webempresa/pages/templates/pages/sample.html
{% extends 'core/base.html' %}
{% block title %}sample{% endblock %}
{% block sections %}
    <section class="page-section about-heading">
      <div class="container">
        <div class="about-heading-content mbtm">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5 forced">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-lower">{{ page.title }}</span>
                </h2>
                <div class="section-content">
                    {{ page.content|safe }}
                    {% if user.is_authenticated%}
                        <p><a href="{% url 'admin:pages_pages_change' page.id %}">Editar</a></p>

                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}